#include "esolver_lj.h"
#include "source_io/module_parameter/parameter.h"
#include "source_cell/module_neighbor/sltk_atom_arrange.h"
#include "source_cell/module_neighbor/sltk_grid_driver.h"
#include "source_io/module_output/output_log.h"
#include "source_io/module_output/cif_io.h"
#include "source_cell/module_neighlist/neighbor_types.h"
#include "source_cell/module_neighlist/neighbor_search.h"
#include "source_base/global_variable.h"
#include "source_base/timer.h"
#ifdef __MPI
#include "source_cell/module_neighlist/domain_decomposition.h"
#include "source_base/parallel_reduce.h"
#endif

#include <algorithm>
#include <array>
#include <cmath>
#include <vector>


namespace ModuleESolver
{

    UnitCellLite ESolver_LJ::change_from_ucell_to_ucell_lite(const UnitCell& ucell)
    {
        UnitCellLite ucell_lite;

        // Set lattice parameters
        ucell_lite.set_lattice(ucell.lat0, ucell.omega, ucell.latvec);

        // Build atom information
        std::vector<int> na;
        std::vector<ModuleBase::Vector3<double>> tau;
        for (int i = 0; i < ucell.ntype; i++) {
            na.push_back(ucell.atoms[i].na);
            for (int j = 0; j < ucell.atoms[i].na; j++) {
                tau.push_back(ucell.atoms[i].tau[j]);
            }
        }
        ucell_lite.set_atoms(ucell.ntype, na, tau);

        return ucell_lite;
    }

void ESolver_LJ::before_all_runners(BaseCell& cell, const Input_para& inp)
{
    cell.require_kind(BaseCell::Kind::unit_cell, __FUNCTION__);
    UnitCell& ucell = static_cast<UnitCell&>(cell);
    lj_potential = 0;
    lj_force.create(ucell.nat, 3);
    lj_virial.create(3, 3);

    ModuleIO::CifParser::write(PARAM.globalv.global_out_dir + "STRU.cif",
                               ucell,
                               "# Generated by ABACUS ModuleIO::CifParser",
                               "data_?");

    // determine the maximum rcut and lj_rcut
    rcut_search_radius(ucell.ntype, inp.mdp.lj_rcut);

    // determine the LJ parameters
    set_c6_c12(ucell.ntype, inp.mdp.lj_rule, inp.mdp.lj_epsilon, inp.mdp.lj_sigma);

    // calculate the energy shift so that LJ energy is zero at rcut
    cal_en_shift(ucell.ntype, inp.mdp.lj_eshift);
}

void ESolver_LJ::runner(BaseCell& cell, const int istep)
{
    static_cast<void>(istep);
    cell.require_kind(BaseCell::Kind::unit_cell, __FUNCTION__);
    UnitCell& ucell = static_cast<UnitCell&>(cell);
    UnitCellLite ucell_lite = change_from_ucell_to_ucell_lite(ucell);
    NeighborSearch neighbor_search;

    // Important! potential, force, virial must be zero per step
    lj_potential = 0;
    lj_force.zero_out();
    lj_virial.zero_out();

    double distance = 0.0;
    ModuleBase::Vector3<double> tau1, tau2, dtau;

    #ifdef __MPI
    {
        ModuleBase::timer::start("ESolverLJ", "mpi_total");
        ModuleBase::timer::start("ESolverLJ", "neigh_init");
        DomainDecomposition decomp;
        decomp.init(MPI_COMM_WORLD, ucell_lite.get_latvec(), ucell_lite.get_lat0(), search_radius, 0.0);
        std::vector<LocalAtom> owned_atoms;
        std::vector<LocalAtom> ghost_atoms;
        decomp.split_owned_atoms_from_ucell(ucell_lite, owned_atoms);
        decomp.exchange_ghost_atoms(owned_atoms, ghost_atoms);
        neighbor_search.init_distributed(owned_atoms, ghost_atoms, search_radius, ucell_lite.get_lat0());
        ModuleBase::timer::end("ESolverLJ", "neigh_init");
        ModuleBase::timer::start("ESolverLJ", "neigh_bld");
        neighbor_search.build_neighbors();
        ModuleBase::timer::end("ESolverLJ", "neigh_bld");

        const NeighborList& neighbor_list = neighbor_search.get_neighbor_list();
        const std::vector<NeighborAtom>& inside_atoms = neighbor_search.get_inside_atoms();
        const std::vector<NeighborAtom>& all_atoms = neighbor_search.get_all_atoms();

        std::vector<int> atom_start(ucell.ntype + 1, 0);
        for (int it = 0; it < ucell.ntype; ++it)
        {
            atom_start[it + 1] = atom_start[it] + ucell.atoms[it].na;
        }

        const std::size_t local_virial_size
            = ModuleNeighList::checked_size_product(inside_atoms.size(), 9, "ESolver_LJ local virial size");
        std::vector<double> potential_by_local_atom(inside_atoms.size(), 0.0);
        std::vector<double> virial_by_local_atom(local_virial_size, 0.0);

        ModuleBase::timer::start("ESolverLJ", "force_loc");
        for (int local_i = 0; local_i < neighbor_list.get_nlocal(); ++local_i)
        {
            const NeighborAtom& center_atom = inside_atoms[local_i];
            const int it = center_atom.atom_type;
            const int ia = center_atom.atom_index;
            const int global_i = atom_start[it] + ia;

            tau1.x = center_atom.position_x;
            tau1.y = center_atom.position_y;
            tau1.z = center_atom.position_z;

            for (int ad = 0; ad < neighbor_list.get_numneigh(local_i); ++ad)
            {
                const NeighborAtom& neighbor_atom = all_atoms[neighbor_list.get_firstneigh(local_i)[ad]];
                tau2.x = neighbor_atom.position_x;
                tau2.y = neighbor_atom.position_y;
                tau2.z = neighbor_atom.position_z;
                int it2 = neighbor_atom.atom_type;
                dtau = (tau1 - tau2) * ucell.lat0;
                distance = dtau.norm();
                if (distance < lj_rcut(it, it2))
                {
                    potential_by_local_atom[local_i] += LJ_energy(distance, it, it2) - en_shift(it, it2);
                    ModuleBase::Vector3<double> f_ij = LJ_force(dtau, it, it2);
                    lj_force(global_i, 0) += f_ij.x;
                    lj_force(global_i, 1) += f_ij.y;
                    lj_force(global_i, 2) += f_ij.z;
                    for (int i = 0; i < 3; ++i)
                    {
                        for (int j = 0; j < 3; ++j)
                        {
                            virial_by_local_atom[local_i * 9 + i * 3 + j] += dtau[i] * f_ij[j];
                        }
                    }
                }
            }
        }
        ModuleBase::timer::end("ESolverLJ", "force_loc");

        double local_potential = 0.0;
        std::array<double, 9> local_virial{};
        for (std::size_t local_i = 0; local_i < potential_by_local_atom.size(); ++local_i)
        {
            local_potential += potential_by_local_atom[local_i];
            for (int component = 0; component < 9; ++component)
            {
                local_virial[component] += virial_by_local_atom[local_i * 9 + component];
            }
        }

        ModuleBase::timer::start("ESolverLJ", "reduce");
        Parallel_Reduce::reduce_all(&local_potential, 1);
        Parallel_Reduce::reduce_all(local_virial.data(), static_cast<int>(local_virial.size()));
        // Existing MD code expects a full global force matrix on each rank.
        // Keeping this reduction preserves current behavior; removing the global
        // force layout requires a distributed MD data model.
        Parallel_Reduce::reduce_all(lj_force.c, lj_force.nr * lj_force.nc);
        ModuleBase::timer::end("ESolverLJ", "reduce");

        lj_potential += local_potential;
        for (int i = 0; i < 3; ++i)
        {
            for (int j = 0; j < 3; ++j)
            {
                lj_virial(i, j) += local_virial[i * 3 + j];
            }
        }
        ModuleBase::timer::end("ESolverLJ", "mpi_total");
    }
    #else
    {
        ModuleBase::timer::start("ESolverLJ", "serial_tot");
        ModuleBase::timer::start("ESolverLJ", "ser_neigh");
        neighbor_search.init(ucell_lite, search_radius);
        neighbor_search.build_neighbors();
        ModuleBase::timer::end("ESolverLJ", "ser_neigh");

        int index = 0;
        const NeighborList& neighbor_list = neighbor_search.get_neighbor_list();
        const std::vector<NeighborAtom>& all_atoms = neighbor_search.get_all_atoms();
        ModuleBase::timer::start("ESolverLJ", "ser_force");
        for (int it = 0; it < ucell.ntype; ++it)
        {
            Atom* atom1 = &ucell.atoms[it];
            for (int ia = 0; ia < atom1->na; ++ia)
            {
                tau1 = atom1->tau[ia];
                for (int ad = 0; ad < neighbor_list.get_numneigh(index); ++ad)
                {
                    const NeighborAtom& neighbor_atom = all_atoms[neighbor_list.get_firstneigh(index)[ad]];
                    tau2.x = neighbor_atom.position_x;
                    tau2.y = neighbor_atom.position_y;
                    tau2.z = neighbor_atom.position_z;
                    int it2 = neighbor_atom.atom_type;
                    dtau = (tau1 - tau2) * ucell.lat0;
                    distance = dtau.norm();
                    if (distance < lj_rcut(it, it2))
                    {
                        lj_potential += LJ_energy(distance, it, it2) - en_shift(it, it2);
                        ModuleBase::Vector3<double> f_ij = LJ_force(dtau, it, it2);
                        lj_force(index, 0) += f_ij.x;
                        lj_force(index, 1) += f_ij.y;
                        lj_force(index, 2) += f_ij.z;
                        LJ_virial(f_ij, dtau);
                    }
                }
                index++;
            }
        }
        ModuleBase::timer::end("ESolverLJ", "ser_force");
        ModuleBase::timer::end("ESolverLJ", "serial_tot");
    }
    #endif

    lj_potential /= 2.0;
    GlobalV::ofs_running << " #TOTAL ENERGY# " << std::setprecision(11) << lj_potential * ModuleBase::Ry_to_eV << " eV"
                         << std::endl;

    // Post treatment for virial
    for (int i = 0; i < 3; ++i)
    {
        for (int j = 0; j < 3; ++j)
        {
            lj_virial(i, j) /= (2.0 * ucell.omega);
        }
    }
}

    double ESolver_LJ::cal_energy()
    {
        return lj_potential;
    }

    void ESolver_LJ::cal_force(BaseCell& cell, ModuleBase::matrix& force)
    {
        cell.require_kind(BaseCell::Kind::unit_cell, __FUNCTION__);
        UnitCell& ucell = static_cast<UnitCell&>(cell);
        force = lj_force;
        ModuleIO::print_force(GlobalV::ofs_running, ucell, "TOTAL-FORCE (eV/Angstrom)", force, false);
    }

    void ESolver_LJ::cal_stress(BaseCell& cell, ModuleBase::matrix& stress)
    {
        cell.require_kind(BaseCell::Kind::unit_cell, __FUNCTION__);
        stress = lj_virial;

        const bool screen = true;
        const bool ry = false;
        ModuleIO::print_stress("TOTAL-STRESS", stress, screen, ry, GlobalV::ofs_running);

        // external stress
        double unit_transform = ModuleBase::RYDBERG_SI / pow(ModuleBase::BOHR_RADIUS_SI, 3) * 1.0e-8;
        double external_stress[3] = {PARAM.inp.press1, PARAM.inp.press2, PARAM.inp.press3};
        for (int i = 0; i < 3; i++)
        {
            stress(i, i) -= external_stress[i] / unit_transform;
        }
    }

    void ESolver_LJ::after_all_runners(BaseCell& cell)
    {
        cell.require_kind(BaseCell::Kind::unit_cell, __FUNCTION__);
        GlobalV::ofs_running << "\n --------------------------------------------" << std::endl;
        GlobalV::ofs_running << std::setprecision(16);
        GlobalV::ofs_running << " !FINAL_ETOT_IS " << lj_potential * ModuleBase::Ry_to_eV << " eV" << std::endl;
        GlobalV::ofs_running << " --------------------------------------------\n\n" << std::endl;
    }

    double ESolver_LJ::LJ_energy(const double& d, const int& i, const int& j) const
    {
        assert(d > 1e-6); // avoid atom overlap
        const double r2 = d * d;
        const double r4 = r2 * r2;
        const double r6 = r2 * r4;
        return lj_c12(i, j) / (r6 * r6) - lj_c6(i, j) / r6;
    }

    ModuleBase::Vector3<double> ESolver_LJ::LJ_force(const ModuleBase::Vector3<double>& dr, const int& i, const int& j) const
    {
        const double d = dr.norm();
        assert(d > 1e-6); // avoid atom overlap
        const double r2 = d * d;
        const double r4 = r2 * r2;
        const double r8 = r4 * r4;
        const double r14 = r8 * r4 * r2;
        double coff = 12.0 * lj_c12(i, j) / r14 - 6.0 * lj_c6(i, j) / r8;
        return dr * coff;
    }

    void ESolver_LJ::LJ_virial(const ModuleBase::Vector3<double>& force, const ModuleBase::Vector3<double>& dtau)
    {
        for (int i = 0; i < 3; ++i)
        {
            for (int j = 0; j < 3; ++j)
            {
                lj_virial(i, j) += dtau[i] * force[j];
            }
        }
    }

    void ESolver_LJ::rcut_search_radius(const int& ntype, const std::vector<double>& rcut)
    {
        lj_rcut.create(ntype, ntype);
        double rcut_max = 0.0;

        if (rcut.size() == 1)
        {
            rcut_max = rcut[0] * ModuleBase::ANGSTROM_AU;
            for (int i = 0; i < ntype; i++)
            {
                for (int j = 0; j <= i; j++)
                {
                    lj_rcut(i, j) = rcut_max;
                    lj_rcut(j, i) = rcut_max;
                }
            }
        }
        else if (rcut.size() == ntype * (ntype + 1) / 2)
        {
            for (int i = 0; i < ntype; i++)
            {
                for (int j = 0; j <= i; j++)
                {
                    int k = i * (i + 1) / 2 + j;
                    lj_rcut(i, j) = rcut[k] * ModuleBase::ANGSTROM_AU;
                    lj_rcut(j, i) = lj_rcut(i, j);
                    rcut_max = std::max(rcut_max, lj_rcut(i, j));
                }
            }
        }

        // set the search radius
        search_radius = rcut_max + 0.01;
    }

    void ESolver_LJ::set_c6_c12(const int& ntype,
                                const int& rule,
                                const std::vector<double>& epsilon,
                                const std::vector<double>& sigma)
    {
        lj_c6.create(ntype, ntype);
        lj_c12.create(ntype, ntype);

        std::vector<double> lj_epsilon = epsilon;
        std::vector<double> lj_sigma = sigma;

        std::transform(begin(lj_epsilon), end(lj_epsilon), begin(lj_epsilon), [](double x) {
            return x / ModuleBase::Ry_to_eV;
        });
        std::transform(begin(lj_sigma), end(lj_sigma), begin(lj_sigma), [](double x) {
            return x * ModuleBase::ANGSTROM_AU;
        });

        if (lj_epsilon.size() != lj_sigma.size())
        {
            ModuleBase::WARNING_QUIT("ESolver_LJ", " the number of lj_epsilon should be equal to lj_sigma ");
        }
        // do not need any combination rules
        else if (lj_sigma.size() == ntype * (ntype + 1) / 2)
        {
            for (int i = 0; i < ntype; i++)
            {
                for (int j = 0; j <= i; j++)
                {
                    int k = i * (i + 1) / 2 + j;
                    double temp = pow(lj_sigma[k], 6);
                    lj_c6(i, j) = 4.0 * lj_epsilon[k] * temp;
                    lj_c12(i, j) = lj_c6(i, j) * temp;
                    lj_c6(j, i) = lj_c6(i, j);
                    lj_c12(j, i) = lj_c12(i, j);
                }
            }
        }
        // combination rule 1
        else if (lj_sigma.size() == ntype && rule == 1)
        {
            for (int i = 0; i < ntype; i++)
            {
                // first determine the diagonal elements
                double temp = pow(lj_sigma[i], 6);
                lj_c6(i, i) = 4.0 * lj_epsilon[i] * temp;
                lj_c12(i, i) = lj_c6(i, i) * temp;

                // then determine the non-diagonal elements
                for (int j = 0; j < i; j++)
                {
                    lj_c6(i, j) = std::sqrt(lj_c6(i, i) * lj_c6(j, j));
                    lj_c12(i, j) = std::sqrt(lj_c12(i, i) * lj_c12(j, j));
                    lj_c6(j, i) = lj_c6(i, j);
                    lj_c12(j, i) = lj_c12(i, j);
                }
            }
        }
        // combination rule 2
        else if (lj_sigma.size() == ntype && rule == 2)
        {
            for (int i = 0; i < ntype; i++)
            {
                for (int j = 0; j <= i; j++)
                {
                    double sigma_ij = (lj_sigma[i] + lj_sigma[j]) / 2.0;
                    double epsilon_ij = std::sqrt(lj_epsilon[i] * lj_epsilon[j]);

                    double temp = pow(sigma_ij, 6);
                    lj_c6(i, j) = 4.0 * epsilon_ij * temp;
                    lj_c12(i, j) = lj_c6(i, j) * temp;
                    lj_c6(j, i) = lj_c6(i, j);
                    lj_c12(j, i) = lj_c12(i, j);
                }
            }
        }
    }

    void ESolver_LJ::cal_en_shift(const int& ntype, const bool& is_shift)
    {
        en_shift.create(ntype, ntype);

        if (is_shift)
        {
            for (int i = 0; i < ntype; i++)
            {
                for (int j = 0; j <= i; j++)
                {
                    en_shift(i, j) = LJ_energy(lj_rcut(i, j), i, j);
                    en_shift(j, i) = en_shift(i, j);
                }
            }
        }
    }
}
