#ifndef ABACUS_SOURCE_HSOLVER_MODULE_GENELPA_ELPA_RUNTIME_CHECK_H
#define ABACUS_SOURCE_HSOLVER_MODULE_GENELPA_ELPA_RUNTIME_CHECK_H


#include <mpi.h>

void validate_elpa_complex_kernel(int kernel, int set_status, MPI_Comm comm);

#endif // ABACUS_SOURCE_HSOLVER_MODULE_GENELPA_ELPA_RUNTIME_CHECK_H
