#!/usr/bin/env python3
"""Generate the immutable data used by ABACUS' native DFT-D3 backend.

The generated files are derived from a pinned s-dftd3 source tree and the
mctc-lib version used by that release.  Neither project is a build-time or a
run-time dependency of ABACUS; they are inputs to this maintainer-only tool.
"""

from __future__ import annotations

import argparse
import hashlib
import math
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Sequence


MAX_ELEMENT = 103
MAX_REFERENCE = 7
PAIR_COUNT = MAX_ELEMENT * (MAX_ELEMENT + 1) // 2

PINNED_INPUT_HASHES = {
    "reference.f90": "6551131d1d2c6fa186de0eb753f862b935bb60024dd74cf0eefb650eed9b126b",
    "r4r2.f90": "c339eec5d337fed885fbb3bff521f9c972bedcf368a435e24e58c110f6dd1925",
    "vdwrad.f90": "3f08b5755bfd643d6dbb56fd544c117145473a4b27138978a25d0475af985575",
    "param.f90": "27d80cb394567154069e12bad881648f7bb0fe71edf9f4b412d9851215d3c2e4",
    "covrad.f90": "fdbd599664a7f113633d96110531d810fdc8e54b6db26d4f584120d9c7cec314",
    "codata2018.f90": "47c4abbc7f9dddb3bba1c89563b45e792304bc56723f1c4b05fc978aa5d3704d",
}

FLOAT_WP_RE = re.compile(
    r"([+-]?(?:(?:\d+(?:\.\d*)?)|(?:\.\d+))(?:[eEdD][+-]?\d+)?)_wp"
)


def fail(message: str) -> "NoReturn":
    raise RuntimeError(message)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    digest.update(path.read_bytes())
    return digest.hexdigest()


def strip_fortran_comments(text: str) -> str:
    return "\n".join(line.split("!", 1)[0] for line in text.splitlines())


def extract_initializer(text: str, declaration: str) -> str:
    start = text.find(declaration)
    if start < 0:
        fail(f"cannot find Fortran declaration containing {declaration!r}")
    start = text.find("[", start)
    end = text.find("]", start)
    if start < 0 or end < 0:
        fail(f"cannot find array initializer for {declaration!r}")
    return strip_fortran_comments(text[start + 1 : end])


def parse_wp_values(fragment: str) -> list[float]:
    return [float(value.replace("d", "e").replace("D", "E")) for value in FLOAT_WP_RE.findall(fragment)]


def parse_integer_initializer(text: str, declaration: str) -> list[int]:
    fragment = extract_initializer(text, declaration)
    return [int(value) for value in re.findall(r"[+-]?\d+", fragment)]


def cxx_float(value: float) -> str:
    if not math.isfinite(value):
        fail("generated D3 data contains a non-finite floating-point value")
    result = format(value, ".17g")
    if not any(marker in result for marker in (".", "e", "E")):
        result += ".0"
    return result


def format_array(values: Sequence[object], formatter=str, columns: int = 6) -> str:
    lines: list[str] = []
    for begin in range(0, len(values), columns):
        row = ", ".join(formatter(value) for value in values[begin : begin + columns])
        lines.append("    " + row + ("," if begin + columns < len(values) else ""))
    return "\n".join(lines)


def generated_header(inputs: Iterable[Path]) -> str:
    entries = "\n".join(f"//   {path.name}: sha256={sha256(path)}" for path in inputs)
    return (
        "// Generated by tools/05_param_generation/generate_d3_data.py; do not edit.\n"
        "// Numerical specification: s-dftd3 v1.5.0 "
        "(c1d5b8d79dbe938431069e9509d704deb1a72d23).\n"
        f"{entries}\n\n"
    )


def parse_c6(reference_text: str) -> list[float]:
    dense = [0.0] * (MAX_REFERENCE * MAX_REFERENCE * PAIR_COUNT)
    pattern = re.compile(
        r"c6ab_view\(\s*(\d+)\s*:\s*(\d+)\s*\)\s*=\s*\[(.*?)\]",
        re.DOTALL,
    )
    seen = 0
    for match in pattern.finditer(reference_text):
        begin = int(match.group(1)) - 1
        end = int(match.group(2))
        values = parse_wp_values(strip_fortran_comments(match.group(3)))
        if len(values) != end - begin:
            fail(f"C6 block {begin + 1}:{end} contains {len(values)} values")
        dense[begin:end] = values
        seen += len(values)
    if seen != len(dense):
        fail(f"expected {len(dense)} dense reference C6 values, parsed {seen}")
    return dense


def parse_named_constant(text: str, name: str) -> float:
    match = re.search(
        rf"::\s*{re.escape(name)}\s*=\s*"
        r"([+-]?(?:(?:\d+(?:\.\d*)?)|(?:\.\d+))(?:[eEdD][+-]?\d+)?)_wp",
        text,
        re.IGNORECASE,
    )
    if not match:
        fail(f"cannot find CODATA constant {name}")
    return float(match.group(1).replace("d", "e").replace("D", "E"))


def angstrom_to_bohr(codata_text: str) -> float:
    planck = parse_named_constant(codata_text, "planck_constant")
    light = parse_named_constant(codata_text, "speed_of_light_in_vacuum")
    alpha = parse_named_constant(codata_text, "fine_structure_constant")
    electron_mass = parse_named_constant(codata_text, "electron_mass")
    pi = float("3.1415926535897932384626433832795029")
    hbar = planck / (2.0 * pi)
    bohr_metre = hbar / (electron_mass * light * alpha)
    return 1.0 / (bohr_metre * 1.0e10)


def pack_reference_data(
    reference_text: str,
    covrad_text: str,
    r4r2_text: str,
    vdwrad_text: str,
    codata_text: str,
) -> dict[str, list[float] | list[int]]:
    counts = parse_integer_initializer(reference_text, "number_of_references(max_elem)")
    if len(counts) != MAX_ELEMENT or max(counts) != MAX_REFERENCE:
        fail("unexpected s-dftd3 reference-count dimensions")

    reference_cn = parse_wp_values(
        extract_initializer(reference_text, "reference_cn(max_ref, max_elem)")
    )
    if len(reference_cn) != MAX_ELEMENT * MAX_REFERENCE:
        fail("unexpected s-dftd3 reference-CN dimensions")

    dense_c6 = parse_c6(reference_text)
    offsets: list[int] = []
    packed_c6: list[float] = []
    for high in range(1, MAX_ELEMENT + 1):
        for low in range(1, high + 1):
            offsets.append(len(packed_c6))
            pair = low + high * (high - 1) // 2  # Fortran's one-based pair index
            base = MAX_REFERENCE * MAX_REFERENCE * (pair - 1)
            for high_ref in range(counts[high - 1]):
                for low_ref in range(counts[low - 1]):
                    packed_c6.append(
                        dense_c6[base + high_ref + MAX_REFERENCE * low_ref]
                    )

    if len(offsets) != PAIR_COUNT:
        fail("unexpected number of packed element pairs")

    aa_to_au = angstrom_to_bohr(codata_text)
    covalent_angstrom = parse_wp_values(extract_initializer(covrad_text, "covalent_rad_2009"))
    if len(covalent_angstrom) < MAX_ELEMENT:
        fail("mctc-lib covalent-radius table is too short")
    covalent = [4.0 / 3.0 * aa_to_au * value for value in covalent_angstrom[:MAX_ELEMENT]]

    r4_over_r2 = parse_wp_values(extract_initializer(r4r2_text, "r4_over_r2"))
    if len(r4_over_r2) < MAX_ELEMENT:
        fail("s-dftd3 r4/r2 table is too short")
    r4r2 = [math.sqrt(0.5 * value * math.sqrt(z)) for z, value in enumerate(r4_over_r2[:MAX_ELEMENT], 1)]

    vdw_angstrom = parse_wp_values(extract_initializer(vdwrad_text, "vdwrad"))
    if len(vdw_angstrom) != PAIR_COUNT:
        fail("unexpected s-dftd3 van-der-Waals-radius dimensions")
    vdw = [aa_to_au * value for value in vdw_angstrom]

    return {
        "counts": [0] + counts,
        "reference_cn": [0.0] * MAX_REFERENCE + reference_cn,
        "offsets": offsets,
        "c6": packed_c6,
        "covalent": [0.0] + covalent,
        "r4r2": [0.0] + r4r2,
        "vdw": vdw,
    }


@dataclass(frozen=True)
class DampingRecord:
    method_id: str
    damping: str
    s6: float = 1.0
    s8: float = 1.0
    s9: float = 0.0
    rs6: float = 1.0
    rs8: float = 1.0
    a1: float = 0.4
    a2: float = 5.0
    alp: float = 14.0


def subroutine(text: str, name: str) -> str:
    begin = text.find(f"subroutine {name}")
    end = text.find(f"end subroutine {name}", begin)
    if begin < 0 or end < 0:
        fail(f"cannot find Fortran subroutine {name}")
    return text[begin:end]


def parse_damping_records(param_text: str, name: str, damping: str) -> list[DampingRecord]:
    body = subroutine(param_text, name)
    pattern = re.compile(
        r"^\s*case\(([^)]*)\)(.*?)(?=^\s*case(?:\(|\s+default)|^\s*end select)",
        re.MULTILINE | re.DOTALL,
    )
    records: list[DampingRecord] = []
    for block in pattern.finditer(body):
        method_ids = re.findall(r"p_[A-Za-z0-9_]+", block.group(1))
        constructor = re.search(r"param\s*=\s*d3_param\((.*?)\)", block.group(2), re.DOTALL)
        if not constructor:
            fail(f"missing d3_param constructor in {name} case {block.group(1)}")
        values = {
            key.lower(): float(value.replace("d", "e").replace("D", "E"))
            for key, value in re.findall(
                r"([A-Za-z0-9_]+)\s*=\s*"
                r"([+-]?(?:(?:\d+(?:\.\d*)?)|(?:\.\d+))(?:[eEdD][+-]?\d+)?)_wp",
                constructor.group(1),
            )
        }
        for method_id in method_ids:
            records.append(DampingRecord(method_id=method_id, damping=damping, **values))
    return records


def parse_method_aliases(param_text: str) -> list[tuple[str, str]]:
    begin = param_text.find("function get_method_id")
    end = param_text.find("end function get_method_id", begin)
    if begin < 0 or end < 0:
        fail("cannot find s-dftd3 get_method_id")
    body = param_text[begin:end]
    aliases: list[tuple[str, str]] = []
    for match in re.finditer(
        r"case\(([^)]*)\)\s*;\s*id\s*=\s*(p_[A-Za-z0-9_]+)", body
    ):
        for alias in re.findall(r'"([^"]+)"', match.group(1)):
            aliases.append((alias, match.group(2)))
    return aliases


def reference_inc(data: dict[str, list[float] | list[int]], inputs: Sequence[Path]) -> str:
    return generated_header(inputs) + "\n".join(
        [
            f"static const unsigned char kReferenceCount[{MAX_ELEMENT + 1}] = {{\n"
            + format_array(data["counts"], str, 16)
            + "\n};\n",
            f"static const double kReferenceCn[{(MAX_ELEMENT + 1) * MAX_REFERENCE}] = {{\n"
            + format_array(data["reference_cn"], cxx_float, 7)
            + "\n};\n",
            f"static const unsigned int kReferenceC6Offset[{PAIR_COUNT}] = {{\n"
            + format_array(data["offsets"], str, 10)
            + "\n};\n",
            f"static const double kReferenceC6[{len(data['c6'])}] = {{\n"
            + format_array(data["c6"], cxx_float, 6)
            + "\n};\n",
            f"static const double kCovalentRadius[{MAX_ELEMENT + 1}] = {{\n"
            + format_array(data["covalent"], cxx_float, 6)
            + "\n};\n",
            f"static const double kR4R2[{MAX_ELEMENT + 1}] = {{\n"
            + format_array(data["r4r2"], cxx_float, 6)
            + "\n};\n",
            f"static const double kVdwRadius[{PAIR_COUNT}] = {{\n"
            + format_array(data["vdw"], cxx_float, 6)
            + "\n};\n",
        ]
    )


def damping_inc(records: Sequence[DampingRecord], inputs: Sequence[Path]) -> str:
    lines = []
    for record in records:
        values = ", ".join(
            cxx_float(value)
            for value in (
                record.s6,
                record.s8,
                record.s9,
                record.rs6,
                record.rs8,
                record.a1,
                record.a2,
                record.alp,
            )
        )
        lines.append(
            f'    {{"{record.method_id}", Damping::{record.damping}, {values}}}'
        )
    return (
        generated_header(inputs)
        + "static const DampingParameterRecord kDampingParameters[] = {\n"
        + ",\n".join(lines)
        + "\n};\n"
    )


def aliases_inc(aliases: Sequence[tuple[str, str]], inputs: Sequence[Path]) -> str:
    lines = [f'    {{"{alias}", "{method_id}"}}' for alias, method_id in aliases]
    return (
        generated_header(inputs)
        + "static const MethodAlias kMethodAliases[] = {\n"
        + ",\n".join(lines)
        + "\n};\n"
    )


def write_or_check(path: Path, content: str, check: bool) -> tuple[bool, bool]:
    current = path.read_text() if path.exists() else None
    if current == content:
        return True, False
    if check:
        print(f"Out of date: {path}", file=sys.stderr)
        return False, False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)
    print(f"wrote {path}")
    return True, True

class HelpFormatter(argparse.HelpFormatter):
    def __init__(self, prog: str) -> None:
        super().__init__(prog, width=80, max_help_position=30)

def main() -> int:
    parser = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=HelpFormatter,
    )
    parser.add_argument(
        "--s-dftd3-root",
        metavar="PATH",
        type=Path,
        required=True,
        help="s-dftd3 source root directory",
    )
    parser.add_argument(
        "--mctc-lib-root",
        metavar="PATH",
        type=Path,
        required=True,
        help="mctc-lib source root directory",
    )
    parser.add_argument(
        "--output-root",
        metavar="PATH",
        type=Path,
        default=Path(__file__).resolve().parents[2],
        help="ABACUS repository root (default: inferred from this script)",
    )
    parser.add_argument("--check", action="store_true", help="fail if checked-in data differ")
    args = parser.parse_args()

    sroot = args.s_dftd3_root.resolve()
    mroot = args.mctc_lib_root.resolve()
    reference = sroot / "src/dftd3/reference.f90"
    r4r2 = sroot / "src/dftd3/data/r4r2.f90"
    vdwrad = sroot / "src/dftd3/data/vdwrad.f90"
    param = sroot / "src/dftd3/param.f90"
    covrad = mroot / "src/mctc/data/covrad.f90"
    codata = mroot / "src/mctc/io/codata2018.f90"
    inputs = [reference, r4r2, vdwrad, param, covrad, codata]
    missing = [str(path) for path in inputs if not path.is_file()]
    if missing:
        fail("missing generator input(s): " + ", ".join(missing))
    for path in inputs:
        actual = sha256(path)
        expected = PINNED_INPUT_HASHES[path.name]
        if actual != expected:
            fail(
                f"unexpected {path.name} checksum: {actual}; expected {expected} "
                "for the pinned s-dftd3 v1.5.0 numerical specification"
            )

    reference_text = reference.read_text()
    param_text = param.read_text()
    data = pack_reference_data(
        reference_text,
        covrad.read_text(),
        r4r2.read_text(),
        vdwrad.read_text(),
        codata.read_text(),
    )
    records = parse_damping_records(param_text, "get_rational_damping", "Rational")
    records += parse_damping_records(param_text, "get_zero_damping", "Zero")
    aliases = parse_method_aliases(param_text)

    data_dir = args.output_root / "source/source_hamilt/module_vdw/data"
    outputs = [
        (
            data_dir / "d3_reference.inc",
            reference_inc(data, [reference, r4r2, vdwrad, covrad, codata]),
        ),
        (
            data_dir / "d3_damping_parameters.inc",
            damping_inc(records, [param]),
        ),
        (
            data_dir / "d3_method_aliases.inc",
            aliases_inc(aliases, [param]),
        ),
    ]
    results = [write_or_check(path, content, args.check) for path, content in outputs]
    if not all(success for success, _ in results):
        return 1
    if args.check:
        print("Check passed")
    elif not any(updated for _, updated in results):
        print("Already up to date")
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except RuntimeError as error:
        print(f"error: {error}", file=sys.stderr)
        raise SystemExit(2)
