

list(APPEND objects
    hamilt_pw.cpp
    op_pw_ekin.cpp
    op_pw_veff.cpp
    op_pw_nl.cpp
    op_pw_meta.cpp
    op_pw_vel.cpp
    op_pw.cpp
    op_pw_proj.cpp
    op_pw_exx.cpp
    op_pw_exx_ace.cpp
    op_pw_exx_pot.cpp
    dftu_base.cpp
    dftu_base_io.cpp
    dftu_base_occ.cpp
    dftu_base_tools.cpp
    yukawa_screening.cpp
    setup_pot.cpp
    setup_pwrho.cpp
    setup_pwwfc.cpp
    uspp_support.cpp
    update_cell_pw.cpp
    setup_dftu_pw.cpp
    deltaspin_pw.cpp
    force_pw_nl.cpp
    force_pw_cc.cpp
    force_pw_scc.cpp
    force_pw.cpp
    force_pw_us.cpp
    force_pw_onsite.cpp
    stress_cc.cpp
    stress_ewa.cpp
    stress_gga.cpp
    stress_mgga.cpp
    stress_har.cpp
    stress_kin.cpp
    stress_loc.cpp
    stress_nl.cpp
    stress_us.cpp
    stress_onsite.cpp
    stress_exx.cpp
    stress_pw.cpp
    vl_pw.cpp
    vnl_pw.cpp
    vnl_pw_alpha.cpp
    vnl_pw_deeq.cpp
    vnl_pw_getvnl.cpp
    vnl_pw_grad.cpp
    vnl_pw_init_vnl.cpp
    vnl_pw_qrad.cpp
    stru_fac.cpp
    stru_fac_k.cpp
    soc.cpp
    elecond.cpp
    fs_nonlocal_tools.cpp
    fs_nonlocal_tools_vkb.cpp
    fs_nonlocal_tools_stress.cpp
    fs_nonlocal_tools_force.cpp
    fs_kin_tools.cpp
    radial_proj.cpp
    onsite_proj.cpp
    onsite_proj_init.cpp
    onsite_proj_overlap.cpp
    onsite_proj_force_stress.cpp
    onsite_proj_tools.cpp
    onsite_proj_tools_becp.cpp
    onsite_proj_tools_dbecp.cpp
    onsite_proj_tools_force.cpp
    onsite_proj_tools_stress.cpp
    onsite_proj_print.cpp
    vsep_pw.cpp
)

add_library(
    module_pwdft
    OBJECT
    ${objects}
)

if(ENABLE_COVERAGE)
  add_coverage(module_pwdft)
endif()

if (BUILD_TESTING)
    if(ENABLE_MPI)
        add_subdirectory(test)
        add_subdirectory(kernels/test)
    endif()
endif()
