name: Build Test
on:
  push:
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - tag: gnu
            build_args: ""
            name: "Build with GNU toolchain"
          - tag: intel
            external_toolchain_args: "--with-intel"
            build_args: ""
            name: "Build with Intel toolchain"

          - tag: gnu
            external_toolchain_args: ""
            build_args: "-DENABLE_LIBXC=ON -DENABLE_MLALGO=ON -DENABLE_LIBRI=ON -DENABLE_DFTD4=ON"
            name: "Build extra components with GNU toolchain"
          - tag: intel
            external_toolchain_args: "--with-intel"
            build_args: "-DENABLE_LIBXC=ON -DENABLE_PEXSI=ON -DENABLE_MLALGO=ON -DENABLE_LIBRI=ON -DENABLE_DFTD4=ON"
            name: "Build extra components with Intel toolchain"

          - tag: cuda
            external_toolchain_args: ""
            build_args: "-DUSE_CUDA=ON"
            name: "Build with CUDA support"
          - tag: gnu
            external_toolchain_args: ""
            build_args: "-DENABLE_LCAO=OFF"
            name: "Build without LCAO"
          - tag: gnu
            external_toolchain_args: ""
            build_args: "-DUSE_ELPA=OFF "
            name: "Build without ELPA"
          - tag: gnu
            external_toolchain_args: ""
            build_args: "-DENABLE_MPI=OFF"
            name: "Build without MPI"
          - tag: gnu
            external_toolchain_args: ""
            build_args: "-DENABLE_MPI=OFF -DENABLE_LCAO=OFF"
            name: "Build without LCAO and MPI"

    name: ${{ matrix.name }}
    container: ghcr.io/deepmodeling/abacus-${{ matrix.tag }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1
        with:
          submodules: recursive

      - name: Install external tools from toolchain
        run: |
          sudo apt update && sudo apt install -y gfortran ninja-build pkg-config xz-utils
          cd toolchain
          ./install_abacus_toolchain_new.sh --with-dftd4=install --dry-run ${{matrix.external_toolchain_args}}
          ./scripts/stage4/install_stage4.sh
          cd ..

      - name: Build
        run: |
          git config --global --add safe.directory `pwd`
          source toolchain/install/setup
          prepend_path CMAKE_PREFIX_PATH ${PEXSI32_ROOT}:${SUPERLU_DIST32_ROOT}:${PARMETIS32_ROOT}:${METIS32_ROOT}:${GKLIB_ROOT}
          rm -rf build
          cmake -B build -G Ninja ${{ matrix.build_args }}
          cmake --build build -j $(nproc)
