name: Dynamic Analysis

on:
  schedule:
    - cron: '0 16 * * 0'
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  test:
    name: Dynamic analysis
    runs-on: X64
    if: github.repository_owner == 'deepmodeling'
    container: ghcr.io/deepmodeling/abacus-gnu
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Install external tools from toolchain
        run: |
          sudo apt update && sudo apt install -y xz-utils ninja-build pkg-config
          cd toolchain
          ./install_abacus_toolchain_new.sh --with-dftd4=install --dry-run -j8
          ./scripts/stage4/install_stage4.sh
          cd ..
      - name: Building
        run: |
          source toolchain/install/setup
          cmake -B build -G Ninja -DENABLE_ASAN=ON -DENABLE_MLALGO=ON -DENABLE_LIBXC=ON
          cmake --build build -j8
          cmake --install build
      - name: Testing
        run: |
          cd tests/integrate
          bash Autotest.sh -n 2 -s true
      - name: Publish Report to Dashboard
        uses: crazy-max/ghaction-github-pages@v5
        if: ${{ ! cancelled() }}
        with:
          target_branch: dashboard
          build_dir: tests/html
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
